kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
rules:
- apiGroups:
  - '*'
  resources:
    - '*'
  verbs:
    - '*'
